<a href="https://colab.research.google.com/github/konrad-l/data_science_bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np.__version__

'1.21.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

**1D Array**

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x= np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

**2D Array**

In [ ]:
x= np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim
# wymiar tablicy

2

In [ ]:
x.shape
# kształt danych (dwa wiersze i dwie kolumny)

(2, 2)

In [ ]:
x.size

4

In [ ]:
x = np.array([[1, 2 , 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape
# kształt tablicy: 2 wiersze, 3 kolumny

(2, 3)

**3D Array**

In [ ]:
x = np.array(
    [[[4, 3, 1],
       [3, 1, 2]],

    [[4, 1, 3],
     [4, 2, 1]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape
# "x" ma kształt:
# 2 tablice
# 2 wiersze
# 3 kolumny

(2, 2, 3)

**Typy danych**

In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.2, 2.1, 3.1])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype="float")
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype="complex")
A.dtype

dtype('complex128')

In [ ]:
A = np.array([1.0, 2.2, 3.3], dtype="int")
A.dtype

dtype('int64')

In [ ]:
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120, 230], dtype=np.uint8)
A.dtype

dtype('uint8')

**Tworzenie tablic**

In [ ]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape=(4,10), dtype = "int")

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.ones(shape=(5,5), dtype = "int")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.full(shape=(3,3), fill_value=4, dtype="int")

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(3,-1)
# mają być 3 wiersze
# ilość kolumn ma dobrać Python

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(-1,3)
# ilość wierszy ma dobrać Python
# mają być 3 kolumny

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

**Podstawowe operacje na tablicach**

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A+B

array([6, 0, 7, 4])

In [ ]:
A-B

array([0, 2, 1, 0])

In [ ]:
A*B

array([ 9, -1, 12,  4])

In [ ]:
A/B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
A * 2 

array([6, 2, 8, 4])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

In [ ]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, -2]])
print(X, "\n")
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1 -2]]


In [ ]:
X*Y
# zwykłe mnożenie - pozycja pierwsza z pierwszą, druga z drugą

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X, Y)
# mnożenie macierzy

array([[  3,  -6],
       [-12,   0]])

In [ ]:
X.dot(Y)
# mnożenie macierzy poprzez metodę "dot"

array([[  3,  -6],
       [-12,   0]])

In [ ]:
Y.dot(X)

array([[ 6, 18],
       [ 3, -3]])

In [ ]:
X @ Y 
# mnożenie macierzowe

array([[  3,  -6],
       [-12,   0]])

**Generowanie liczb pseudolosowych**

In [3]:
np.random.seed(0)

In [6]:
np.random.randn()

0.9787379841057392

In [7]:
np.random.randn(10)
# 10 losowych liczb 
# rozkład normalny standardowy

array([ 2.2408932 ,  1.86755799, -0.97727788,  0.95008842, -0.15135721,
       -0.10321885,  0.4105985 ,  0.14404357,  1.45427351,  0.76103773])

In [9]:
np.random.randn(10,4)
# liczba pierwsza - wiersze
# liczba druga - kolumny
# rozkład normalny

array([[-1.18063218, -0.02818223,  0.42833187,  0.06651722],
       [ 0.3024719 , -0.63432209, -0.36274117, -0.67246045],
       [-0.35955316, -0.81314628, -1.7262826 ,  0.17742614],
       [-0.40178094, -1.63019835,  0.46278226, -0.90729836],
       [ 0.0519454 ,  0.72909056,  0.12898291,  1.13940068],
       [-1.23482582,  0.40234164, -0.68481009, -0.87079715],
       [-0.57884966, -0.31155253,  0.05616534, -1.16514984],
       [ 0.90082649,  0.46566244, -1.53624369,  1.48825219],
       [ 1.89588918,  1.17877957, -0.17992484, -1.07075262],
       [ 1.05445173, -0.40317695,  1.22244507,  0.20827498]])

In [10]:
np.random.rand()
# rozkład jednostajny na przedziale

0.8817353618548528

In [11]:
np.random.rand(10)

array([0.69253159, 0.72525428, 0.50132438, 0.95608363, 0.6439902 ,
       0.42385505, 0.60639321, 0.0191932 , 0.30157482, 0.66017354])

In [12]:
np.random.rand(10, 2)

array([[0.29007761, 0.61801543],
       [0.4287687 , 0.13547406],
       [0.29828233, 0.56996491],
       [0.59087276, 0.57432525],
       [0.65320082, 0.65210327],
       [0.43141844, 0.8965466 ],
       [0.36756187, 0.43586493],
       [0.89192336, 0.80619399],
       [0.70388858, 0.10022689],
       [0.91948261, 0.7142413 ]])

In [13]:
np.random.randint(10)

5

In [14]:
np.random.randint(low=10, high=101)

38

In [15]:
np.random.randint(low=10, high=101, size=10)

array([12, 37, 93, 99, 33, 63, 61, 56, 30, 63])

In [17]:
np.random.choice([4,2,1,3])

3

In [18]:
np.random.choice(["python","java","sql"])

'java'

In [20]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.random.shuffle(data)
data

array([4, 8, 1, 0, 5, 2, 6, 3, 7, 9])

**Podstawowe funkcje**

In [22]:
np.exp(1)

2.718281828459045

In [23]:
np.sqrt(9)

3.0

In [24]:
np.all([2, 3, 1])
# sprawdza czy wszystkie są prawdziwe

True

In [26]:
np.any([1,0,0])
# funkcja sprawdza czy która kolwiek zmienna jest "prawdziwa"

True

In [29]:
bool(6.3)

True

In [32]:
A = np.random.rand(5)
A
# rozkład jednostajny
# randn - rozkład normalny

array([0.87457296, 0.94411975, 0.60825287, 0.59665541, 0.78364425])

In [34]:
np.argmax(A)
# sprawdza gdzie jest nawiększy argument w przesłanym zbiorze

1

In [35]:
A[np.argmax(A)]

0.9441197509175635

In [36]:
np.argmin(A)

3

In [38]:
np.argsort(A)
# sortowanie argumentów od najmniejszego do największego

array([3, 2, 4, 0, 1])

In [39]:
np.max(A)

0.9441197509175635

In [40]:
np.min(A)

0.5966554062950531

In [41]:
np.mean(A)

0.7614490452027028

In [42]:
np.median(A)

0.7836442453018885

In [44]:
np.std(A)
# odchylenie standardowe

0.139487810214026

**Indeksowanie, wycinanie**

In [93]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [47]:
A[2]

2

In [48]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [54]:
A[:2]

array([0, 1])

In [55]:
A[[0,2]]


array([0, 2])

In [56]:
A[-1]

19

In [57]:
A[10:15]

array([10, 11, 12, 13, 14])

In [94]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [95]:
A[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [96]:
A[:,0]

array([ 0,  5, 10, 15])

In [97]:
A[:,-1]

array([ 4,  9, 14, 19])

In [98]:
A[:,-2]

array([ 3,  8, 13, 18])

In [99]:
A[1,1]

6

In [100]:
A[1,3]

8

In [102]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [105]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

**Iteracja po tablicach**

In [106]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [107]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [108]:
for row in A:
  print(row[0])

0
5
10
15


In [109]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [110]:
for item in A.flat:
  print(item)
# wypłaszczenie tablicy

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


**Zmiana rozmiaru tablicy**

In [112]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [113]:
A.shape

(4, 5)

In [114]:
A.reshape(5,4)
# zmiana rozmiaru tablicy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [117]:
A.ravel()
# wypłaszczy tablicę

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [118]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

**Maski logiczne**

In [129]:
A = np.arange(start= -10, stop= 10, step= 0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [130]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [131]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [132]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [133]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [134]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])