<a href="https://colab.research.google.com/github/konrad-l/data_science_bootcamp/blob/main/01_wprowadzenie/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import numpy as np
np.__version__

'1.21.5'

**Norma wektora, długość wektora w R^2**

In [2]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [3]:
np.linalg.norm(v1)
# funkcja do obliczenia wektora v1

4.0

In [4]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [5]:
np.linalg.norm(v1)

4.123105625617661

**Norma euklidesowa w R^n**

In [6]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2)

19.209372712298546

**Odległość dwóch punktów na płaszczyźnie**

In [8]:
p = np.array([3,0])
q = np.array([0,4])

np.linalg.norm(p-q)

5.0

**Odległość dwóćh punktów w przestrzeni R^n**

In [10]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])

np.linalg.norm(p-q)
# większy wymiar macierzy, można zwiększyć wymiar dodając kolejne liczby

5.0990195135927845

**Mnożenie macierzy**

In [12]:
X = np.array([[5, 3], [3, 9]])
Y = np.array([[1], [-1]])
print(X, "\n")
print(Y)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [13]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [15]:
Z.shape

(2, 1)

In [25]:
X = np.array([[2, -1, 3],
              [3, 1, 0]])
Y = np.array([[2, 1, -1],
              [0, -1, 2],
              [3, 2 ,0]])
print(X, "\n")
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [26]:
np.dot(X, Y)

array([[13,  9, -4],
       [ 6,  2, -1]])

**Wyznacznik macierzy**

In [29]:
A = np.array([[2,4], [-1,3]])
round(np.linalg.det(A))

10

**Ślad macierzy**

In [30]:
A = np.array([[2,4], [-1,3]])
np.trace(A)

5

**Macierz jednostkowa**

In [31]:
np.eye(5, dtype="int")

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [32]:
np.eye(3)
# domyślnie zmienne typu "float"

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Macierz odwrotna**

In [34]:
B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [36]:
np.set_printoptions(precision=4, suppress= True)
# zaokrąglanie

np.dot(A, B)
# mnożenie macierzy A*B

array([[1., 0.],
       [0., 1.]])

In [37]:
np.dot(B, A)

array([[ 1., -0.],
       [ 0.,  1.]])

**Macierz transponowana**

In [39]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

In [43]:
A.T
# transponowanie poprzez skrót "T"

array([[ 2, -1],
       [ 4,  3]])

**Rozwiązywanie układów równań**

In [44]:
A = np.array([[2, 4], [1, -1]])
print(A)

[[ 2  4]
 [ 1 -1]]


In [45]:
B = np.array([[10], [-1]])
print(B)

[[10]
 [-1]]


In [49]:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X
# mnożenie macierzy odwrotnej A i wektor wyrazów wolnych B

array([[1.],
       [2.]])

In [50]:
X.shape

(2, 1)